services:
  utsuki-bot-net:
    image: utsuki-bot-net
    container_name: utsuki-bot-net
    restart: always
    environment:
      DISCORD_TOKEN_UTSUKI: ${DISCORD_TOKEN_UTSUKI}
      AI_ENDPOINT: ${AI_ENDPOINT}
      API_KEY_WEATHER: ${API_KEY_WEATHER}
